"""Generate downloadable PDF and DOCX contract-analysis reports."""

from __future__ import annotations

import io
import re
from datetime import datetime
from typing import Any
from xml.sax.saxutils import escape

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


REPORT_DISCLAIMER = (
    "This report was generated by an automated legal-contract analysis "
    "prototype. It is provided for informational purposes only and does "
    "not constitute legal advice. Contract terms and model predictions "
    "should be reviewed by a qualified legal professional."
)


def sanitize_filename(filename: str | None) -> str:
    """Create a safe filename for downloaded reports."""

    original_name = filename or "contract"

    stem = original_name.rsplit(".", 1)[0]
    cleaned = re.sub(r"[^A-Za-z0-9_-]+", "_", stem).strip("_")

    return cleaned or "contract"


def format_datetime(value: Any) -> str:
    """Convert a stored ISO datetime into a readable report date."""

    if not value:
        return datetime.now().strftime("%d %B %Y, %H:%M")

    try:
        parsed = datetime.fromisoformat(str(value))
        return parsed.strftime("%d %B %Y, %H:%M")
    except ValueError:
        return str(value)


def safe_text(value: Any, fallback: str = "Not specified") -> str:
    """Convert unknown values into safe readable text."""

    if value is None:
        return fallback

    text = str(value).strip()

    return text or fallback


def confidence_percentage(clause: dict[str, Any]) -> str:
    """Convert stored model confidence to a percentage."""

    try:
        confidence = float(
            clause.get("clause_type_confidence", 0.0) or 0.0
        )
    except (TypeError, ValueError):
        confidence = 0.0

    confidence = max(0.0, min(confidence, 1.0))

    return f"{confidence * 100:.1f}%"


def get_contract_report_data(
    contract_data: dict[str, Any],
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Safely extract analysis and clause data."""

    analysis = contract_data.get("analysis", {})
    clauses = contract_data.get("clauses", [])

    if not isinstance(analysis, dict):
        analysis = {}

    if not isinstance(clauses, list):
        clauses = []

    valid_clauses = [
        clause
        for clause in clauses
        if isinstance(clause, dict)
    ]

    return analysis, valid_clauses


def build_pdf_report(
    contract_data: dict[str, Any],
) -> bytes:
    """Build a PDF contract-analysis report and return its bytes."""

    analysis, clauses = get_contract_report_data(contract_data)

    output = io.BytesIO()

    document = SimpleDocTemplate(
        output,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Legal Contract Analysis Report",
        author="Legal Contract Analyzer",
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        alignment=TA_CENTER,
        spaceAfter=12,
    )

    section_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#3B2F20"),
        spaceBefore=10,
        spaceAfter=7,
    )

    clause_title_style = ParagraphStyle(
        "ClauseHeading",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#5E4624"),
        spaceBefore=8,
        spaceAfter=5,
    )

    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        spaceAfter=5,
    )

    small_style = ParagraphStyle(
        "SmallText",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#555555"),
    )

    warning_style = ParagraphStyle(
        "WarningText",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#A13E35"),
        backColor=colors.HexColor("#FBEDEC"),
        borderColor=colors.HexColor("#D9857E"),
        borderWidth=0.5,
        borderPadding=6,
        spaceBefore=4,
        spaceAfter=7,
    )

    story: list[Any] = []

    story.append(
        Paragraph(
            "Legal Contract Analysis Report",
            title_style,
        )
    )

    story.append(
        Paragraph(
            escape(
                safe_text(
                    contract_data.get("filename"),
                    "Unnamed contract",
                )
            ),
            ParagraphStyle(
                "Filename",
                parent=body_style,
                alignment=TA_CENTER,
                fontSize=11,
                textColor=colors.HexColor("#555555"),
                spaceAfter=14,
            ),
        )
    )

    summary_rows = [
        [
            "Contract type",
            safe_text(analysis.get("contract_type")),
        ],
        [
            "Overall risk",
            safe_text(analysis.get("overall_risk"), "Unknown"),
        ],
        [
            "Total clauses",
            safe_text(
                analysis.get("total_clauses"),
                str(len(clauses)),
            ),
        ],
        [
            "Risky clauses",
            safe_text(analysis.get("risky_clauses"), "0"),
        ],
        [
            "Manual-review clauses",
            safe_text(
                analysis.get("manual_review_clauses"),
                "0",
            ),
        ],
        [
            "Report generated",
            format_datetime(contract_data.get("created_at")),
        ],
    ]

    summary_table = Table(
        [
            [
                Paragraph(
                    f"<b>{escape(str(label))}</b>",
                    body_style,
                ),
                Paragraph(
                    escape(str(value)),
                    body_style,
                ),
            ]
            for label, value in summary_rows
        ],
        colWidths=[55 * mm, 105 * mm],
        hAlign="LEFT",
    )

    summary_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.HexColor("#F2E8D5"),
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#C8B99C"),
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP",
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
            ]
        )
    )

    story.append(summary_table)
    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "Contract Summary",
            section_style,
        )
    )

    story.append(
        Paragraph(
            escape(
                safe_text(
                    analysis.get("summary"),
                    "No contract summary was available.",
                )
            ),
            body_style,
        )
    )

    missing_fields = analysis.get("missing_fields", [])

    if not isinstance(missing_fields, list):
        missing_fields = []

    story.append(
        Paragraph(
            "Missing or Incomplete Information",
            section_style,
        )
    )

    if missing_fields:
        for item in missing_fields:
            story.append(
                Paragraph(
                    f"• {escape(safe_text(item))}",
                    body_style,
                )
            )
    else:
        story.append(
            Paragraph(
                "No supported missing fields were detected.",
                body_style,
            )
        )

    confidence_summary = analysis.get(
        "confidence_summary",
        {},
    )

    if not isinstance(confidence_summary, dict):
        confidence_summary = {}

    story.append(
        Paragraph(
            "Classification Confidence Summary",
            section_style,
        )
    )

    confidence_rows = [
        ["Confidence level", "Clause count"],
        [
            "High",
            safe_text(confidence_summary.get("High"), "0"),
        ],
        [
            "Medium",
            safe_text(confidence_summary.get("Medium"), "0"),
        ],
        [
            "Low",
            safe_text(confidence_summary.get("Low"), "0"),
        ],
    ]

    confidence_table = Table(
        confidence_rows,
        colWidths=[80 * mm, 80 * mm],
    )

    confidence_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#D8C49A"),
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#B8A77F"),
                ),
                (
                    "ALIGN",
                    (1, 1),
                    (1, -1),
                    "CENTER",
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
            ]
        )
    )

    story.append(confidence_table)

    story.append(PageBreak())

    story.append(
        Paragraph(
            "Detailed Clause Analysis",
            section_style,
        )
    )

    if not clauses:
        story.append(
            Paragraph(
                "No analyzed clauses were available.",
                body_style,
            )
        )

    for clause in clauses:
        clause_number = safe_text(
            clause.get("clause_number"),
            "Unknown",
        )

        clause_type = safe_text(
            clause.get("clause_type"),
            "Not classified",
        )

        story.append(
            Paragraph(
                (
                    f"Clause {escape(clause_number)} — "
                    f"{escape(clause_type)}"
                ),
                clause_title_style,
            )
        )

        details_rows = [
            [
                "Risk level",
                safe_text(clause.get("risk_level"), "Unknown"),
            ],
            [
                "Confidence",
                (
                    f"{safe_text(clause.get('confidence_label'), 'Unknown')} "
                    f"({confidence_percentage(clause)})"
                ),
            ],
            [
                "Review status",
                safe_text(
                    clause.get("review_status"),
                    (
                        "Needs manual review"
                        if clause.get("needs_manual_review")
                        else "Manual review not required"
                    ),
                ),
            ],
            [
                "Party affected",
                safe_text(
                    clause.get("party_affected"),
                    "Not identified",
                ),
            ],
            [
                "Classification source",
                safe_text(
                    clause.get("clause_type_source"),
                    "Unknown",
                ),
            ],
        ]

        detail_table = Table(
            [
                [
                    Paragraph(
                        f"<b>{escape(str(label))}</b>",
                        small_style,
                    ),
                    Paragraph(
                        escape(str(value)),
                        small_style,
                    ),
                ]
                for label, value in details_rows
            ],
            colWidths=[48 * mm, 112 * mm],
        )

        detail_table.setStyle(
            TableStyle(
                [
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.35,
                        colors.HexColor("#D4CCBE"),
                    ),
                    (
                        "BACKGROUND",
                        (0, 0),
                        (0, -1),
                        colors.HexColor("#F5F1EA"),
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "TOP",
                    ),
                    (
                        "LEFTPADDING",
                        (0, 0),
                        (-1, -1),
                        5,
                    ),
                    (
                        "RIGHTPADDING",
                        (0, 0),
                        (-1, -1),
                        5,
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        4,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        4,
                    ),
                ]
            )
        )

        story.append(detail_table)
        story.append(Spacer(1, 6))

        if clause.get("needs_manual_review"):
            story.append(
                Paragraph(
                    (
                        "<b>Manual review required:</b> "
                        + escape(
                            safe_text(
                                clause.get("manual_review_reason"),
                                (
                                    "The clause classification should "
                                    "be checked manually."
                                ),
                            )
                        )
                    ),
                    warning_style,
                )
            )

        story.append(
            Paragraph(
                "<b>Clause text</b>",
                body_style,
            )
        )

        story.append(
            Paragraph(
                escape(
                    safe_text(
                        clause.get("text")
                        or clause.get("preview"),
                        "No clause text available.",
                    )
                ),
                body_style,
            )
        )

        story.append(
            Paragraph(
                "<b>Risk reason</b>",
                body_style,
            )
        )

        story.append(
            Paragraph(
                escape(
                    safe_text(
                        clause.get("risk_reason"),
                        "No risk reason was recorded.",
                    )
                ),
                body_style,
            )
        )

        story.append(
            Paragraph(
                "<b>Recommended action</b>",
                body_style,
            )
        )

        story.append(
            Paragraph(
                escape(
                    safe_text(
                        clause.get("recommended_action"),
                        "Manual legal review is recommended.",
                    )
                ),
                body_style,
            )
        )

        story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "Legal Disclaimer",
            section_style,
        )
    )

    story.append(
        Paragraph(
            escape(REPORT_DISCLAIMER),
            small_style,
        )
    )

    document.build(story)

    return output.getvalue()


def add_docx_label_value(
    document: Document,
    label: str,
    value: Any,
) -> None:
    """Add one bold-label paragraph to a DOCX document."""

    paragraph = document.add_paragraph()

    label_run = paragraph.add_run(f"{label}: ")
    label_run.bold = True

    paragraph.add_run(safe_text(value))


def build_docx_report(
    contract_data: dict[str, Any],
) -> bytes:
    """Build a DOCX contract-analysis report and return its bytes."""

    analysis, clauses = get_contract_report_data(contract_data)

    document = Document()

    section = document.sections[0]
    section.top_margin = Inches(0.65)
    section.bottom_margin = Inches(0.65)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

    title = document.add_heading(
        "Legal Contract Analysis Report",
        level=0,
    )
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = document.add_paragraph(
        safe_text(
            contract_data.get("filename"),
            "Unnamed contract",
        )
    )
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    document.add_heading("Report Overview", level=1)

    add_docx_label_value(
        document,
        "Contract type",
        analysis.get("contract_type"),
    )
    add_docx_label_value(
        document,
        "Overall risk",
        analysis.get("overall_risk", "Unknown"),
    )
    add_docx_label_value(
        document,
        "Total clauses",
        analysis.get("total_clauses", len(clauses)),
    )
    add_docx_label_value(
        document,
        "Risky clauses",
        analysis.get("risky_clauses", 0),
    )
    add_docx_label_value(
        document,
        "Manual-review clauses",
        analysis.get("manual_review_clauses", 0),
    )
    add_docx_label_value(
        document,
        "Report generated",
        format_datetime(contract_data.get("created_at")),
    )

    document.add_heading("Contract Summary", level=1)
    document.add_paragraph(
        safe_text(
            analysis.get("summary"),
            "No contract summary was available.",
        )
    )

    document.add_heading(
        "Missing or Incomplete Information",
        level=1,
    )

    missing_fields = analysis.get("missing_fields", [])

    if not isinstance(missing_fields, list):
        missing_fields = []

    if missing_fields:
        for field in missing_fields:
            document.add_paragraph(
                safe_text(field),
                style="List Bullet",
            )
    else:
        document.add_paragraph(
            "No supported missing fields were detected."
        )

    document.add_heading(
        "Classification Confidence Summary",
        level=1,
    )

    confidence_summary = analysis.get(
        "confidence_summary",
        {},
    )

    if not isinstance(confidence_summary, dict):
        confidence_summary = {}

    confidence_table = document.add_table(
        rows=4,
        cols=2,
    )

    confidence_table.style = "Table Grid"

    confidence_table.cell(0, 0).text = "Confidence level"
    confidence_table.cell(0, 1).text = "Clause count"

    for row_index, label in enumerate(
        ["High", "Medium", "Low"],
        start=1,
    ):
        confidence_table.cell(row_index, 0).text = label
        confidence_table.cell(row_index, 1).text = safe_text(
            confidence_summary.get(label),
            "0",
        )

    document.add_page_break()
    document.add_heading("Detailed Clause Analysis", level=1)

    if not clauses:
        document.add_paragraph(
            "No analyzed clauses were available."
        )

    for clause in clauses:
        clause_number = safe_text(
            clause.get("clause_number"),
            "Unknown",
        )

        clause_type = safe_text(
            clause.get("clause_type"),
            "Not classified",
        )

        document.add_heading(
            f"Clause {clause_number} — {clause_type}",
            level=2,
        )

        details_table = document.add_table(
            rows=5,
            cols=2,
        )
        details_table.style = "Table Grid"

        details = [
            (
                "Risk level",
                safe_text(
                    clause.get("risk_level"),
                    "Unknown",
                ),
            ),
            (
                "Confidence",
                (
                    f"{safe_text(clause.get('confidence_label'), 'Unknown')} "
                    f"({confidence_percentage(clause)})"
                ),
            ),
            (
                "Review status",
                safe_text(
                    clause.get("review_status"),
                    (
                        "Needs manual review"
                        if clause.get("needs_manual_review")
                        else "Manual review not required"
                    ),
                ),
            ),
            (
                "Party affected",
                safe_text(
                    clause.get("party_affected"),
                    "Not identified",
                ),
            ),
            (
                "Classification source",
                safe_text(
                    clause.get("clause_type_source"),
                    "Unknown",
                ),
            ),
        ]

        for row_index, (label, value) in enumerate(details):
            details_table.cell(row_index, 0).text = label
            details_table.cell(row_index, 1).text = value

        if clause.get("needs_manual_review"):
            warning = document.add_paragraph()
            warning_run = warning.add_run(
                "Manual review required: "
            )
            warning_run.bold = True

            warning.add_run(
                safe_text(
                    clause.get("manual_review_reason"),
                    (
                        "The clause classification should "
                        "be checked manually."
                    ),
                )
            )

        add_docx_label_value(
            document,
            "Clause text",
            clause.get("text") or clause.get("preview"),
        )

        add_docx_label_value(
            document,
            "Risk reason",
            clause.get("risk_reason"),
        )

        add_docx_label_value(
            document,
            "Recommended action",
            clause.get("recommended_action"),
        )

        document.add_paragraph()

    document.add_heading("Legal Disclaimer", level=1)

    disclaimer_paragraph = document.add_paragraph(
        REPORT_DISCLAIMER
    )

    for run in disclaimer_paragraph.runs:
        run.italic = True
        run.font.size = Pt(9)

    output = io.BytesIO()
    document.save(output)

    return output.getvalue()